<?php
$response = array(
    'status' => "",
    'message' => ""
);

function connect()
{
    global $response;

    $conn = mysqli_connect(DATABASE_HOST, DATABASE_USER, DATABASE_PW, DATABASE_NAME);

    if (mysqli_connect_errno()) {

        echo "<script type='text/javascript'> alert('BAD INTERNAL ERROR'); </script>";
    } else {

        mysqli_select_db($conn, "airline");
    }

    return $conn;
}

function sanitize($input)
{
    $input = strip_tags($input);
    $input = htmlentities($input);
    $input = stripcslashes($input);

    return $input;
}

function createMatrix()
{
    $con = connect();

    if (mysqli_query($con, " SHOW TABLES LIKE 'seats' ")) {

        if (mysqli_affected_rows($con) == 1) {

            mysqli_query($con, "TRUNCATE TABLE seats");
        }
    } else {

        mysqli_query($con, "CREATE TABLE seats (
                                                rowId INT(6) PRIMARY KEY,
                                                columnId VARCHAR(1) PRIMARY KEY,
                                                status int(1) ,
                                                owner VARCHAR(50)
                                     
                                                 )");
    }

    mysqli_close($con);
}

function register_user($con)
{

    /* protection against sql injection */
    $username_tosend = mysqli_real_escape_string($con, $_POST['username']);
    $password_tosend = $_POST['password'];

    if ($stmt = mysqli_prepare($con, 'SELECT id, password FROM accounts WHERE username = ?')) {

        mysqli_stmt_bind_param($stmt, 's', $username_tosend);

        if (mysqli_stmt_execute($stmt) == false) {

            echo "<script type='text/javascript'> alert('BAD INTERNAL ERROR');
                                                  window.location.href = 'login.php';
                 </script>";

            mysqli_stmt_close($stmt);
            return;
        }

        mysqli_stmt_store_result($stmt);

        if (mysqli_stmt_affected_rows($stmt) > 0) {

            echo "<script type='text/javascript'> alert('Username exists, please choose another!');
                                                  window.location.href = 'login.php';
                 </script>";
        } else {

            if ($stmt = mysqli_prepare($con, 'INSERT INTO accounts (username, password) VALUES (?, ?)')) {

                /* salt generated by default */
                $password = password_hash($password_tosend, PASSWORD_DEFAULT);
                mysqli_stmt_bind_param($stmt, 'ss', $username_tosend, $password);

                if (mysqli_stmt_execute($stmt) == false) {

                    echo "<script type='text/javascript'> alert('BAD INTERNAL ERROR');
                                                          window.location.href = 'login.php';
                          </script>";

                    mysqli_stmt_close($stmt);
                    return;
                }

                echo "<script type='text/javascript'> alert('You have successfully registered, you can now login!');
                                                      window.location.href = 'login.php';
                      </script>";
            } else {

                // die('Could not prepare statement!');
                echo "<script type='text/javascript'> alert('BAD INTERNAL ERROR'); </script>";
                mysqli_close($con);
            }
        }

        mysqli_stmt_free_result($stmt);
        mysqli_stmt_close($stmt);
    } else {

        // die('Could not prepare statement!');
        echo "<script type='text/javascript'> alert('BAD INTERNAL ERROR'); 
                                              window.location.href = 'login.php';
              </script>";
        mysqli_close($con);
    }
}

function login_user($con)
{

    /* protection against sql injection */
    $username_tosend = mysqli_real_escape_string($con, $_POST['username']);
    $password_tosend = $_POST['password'];

    if ($stmt = mysqli_prepare($con, 'SELECT id, password FROM accounts WHERE username = ?')) {

        mysqli_stmt_bind_param($stmt, 's', $username_tosend);

        if (mysqli_stmt_execute($stmt) == false) {
            echo "<script type='text/javascript'> alert('BAD INTERNAL ERROR');
                                                  window.location.href = 'login.php';
                  </script>";

            mysqli_stmt_close($stmt);
            return;
        }

        mysqli_stmt_store_result($stmt);

        if (mysqli_stmt_affected_rows($stmt) > 0) {

            mysqli_stmt_bind_result($stmt, $id, $password);
            mysqli_stmt_fetch($stmt);

            if (password_verify($password_tosend, $password)) {

                startSession();
                $_SESSION['loggedin'] = TRUE;
                $_SESSION['name'] = $username_tosend;
                $_SESSION['id'] = $id;
                $_SESSION['time'] = time();

                header('Location: index.php');
            } else {

                echo "<script type='text/javascript'> alert('Wrong password');
                                                      window.location.href = 'login.php'; 
                      </script>";
            }
        } else {

            echo "<script type='text/javascript'> alert('Wrong username');
                                                  window.location.href = 'login.php'
                  </script>";
        }

        mysqli_stmt_free_result($stmt);
        mysqli_stmt_close($stmt);
    } else {

        // die('Could not prepare statement!');
        echo "<script type='text/javascript'> alert('BAD INTERNAL ERROR');
                                              window.location.href = 'login.php';
              </script>";
        mysqli_close($con);
    }
}

function get_map()
{
    $con = connect();

    if ($stmt = mysqli_prepare($con, 'SELECT * FROM seats ORDER BY rowId,columnId')) {

        mysqli_stmt_execute($stmt);
        mysqli_stmt_store_result($stmt);

        mysqli_stmt_bind_result($stmt, $row, $col, $status, $owner);

        $k = 0;
        $i = 0;
        $booked = 0;
        $avaible = 0;
        $sold = 0;
        $result = array();
        $temp = array();
        $letter = range('A', 'Z');

        while (mysqli_stmt_fetch($stmt)) {

            $temp = [
                $row,
                $col,
                $status,
                $owner
            ];

            $result[$k] = $temp;

            $k ++;
        }

        $k = 0;

        echo "<div class='table_limiter'> <table class='matrix'>";

        for ($i = 0; $i < SEAT_ROW; $i ++) {
            /* start of row */
            //if (($i % SEAT_COLUMN) == 0)
                echo "<tr>";

            for ($j = 0; $j < SEAT_COLUMN; $j ++) {

                if (! isset($_SESSION['loggedin']))
                    echo " <td> <button id=" . ($i + 1) . "-" . $letter[$j] . " ";
                else
                    echo " <td> <button id=" . ($i + 1) . "-" . $letter[$j] . " onclick='reserveSeat(this.id)'";

                // if not loggen disable button
                if (! isset($_SESSION['loggedin']))
                    echo "disabled";

                if (sizeof($result, 0) != 0) {

                    if (($i + 1) == $result[$k][0] && $letter[$j] == $result[$k][1]) {

                        if ($result[$k][2] == 0) {

                            echo " style='background-color:green'";
                            $avaible ++;
                        } // if the seat is booked
                        else if ($result[$k][2] == 1) {

                            if (isset($_SESSION['loggedin'])) {

                                // if i'm booked and the seat is mine
                                if ($result[$k][3] == $_SESSION['name'])
                                    echo " style='background-color:yellow'";
                                else
                                    echo " style='background-color:orange'";
                            } else
                                echo " style='background-color:orange'";

                            $booked ++;
                        } // if the seat has been bought
                        else if ($result[$k][2] == 2) {
                            echo " style='background-color:red' disabled";
                            $sold ++;
                        }

                        unset($result[$k]);
                        $k ++;
                    } else {
                        echo " style='background-color:green'";
                        $avaible ++;
                    }
                } else {
                    echo " style='background-color:green'";
                    $avaible ++;
                }

                echo ">" . ($i + 1) . $letter[$j] . "</button></td>";
            }

            echo "</tr>";
        }

        echo "</table> </div>";

        mysqli_stmt_free_result($stmt);
        mysqli_stmt_close($stmt);

        echo "
              <div class='seatDescription'>
                <div class='front'>MAP REPORT</div>
                <p ><i  class='fas fa-chair' aria-hidden='true' style='color:black'></i>   Total Seat &emsp;&emsp;&ensp;&nbsp; <span id='total'>" . SEAT_ROW * SEAT_COLUMN . "</span></p>
                <p ><i  class='fas fa-chair' aria-hidden='true' style='color:green'></i>   Available Seat &emsp;&nbsp;<span id='available'>" . $avaible . "</span></p>
                <p ><i  class='fas fa-chair' aria-hidden='true' style='color: orange'></i> Booked Seat &emsp;&emsp;<span id='booked'>" . $booked . "</span></p>
                <p ><i id='sold' class='fas fa-chair' aria-hidden='true' style='color: red'></i>    Sold Seat &emsp;&emsp;&emsp;&nbsp;<span id='sold'>" . $sold . "</span></p>";

        if (isset($_SESSION['loggedin']))
            echo " <a id='reload' onclick='checkSeats()' style='text-decoration:none'><i class='fas fa-sync'></i>  Reload Map</a>";

        echo "</div>";
    } else {

        echo "<script type='text/javascript'> alert('BAD INTERNAL ERROR'); </script>";
        mysqli_close($con);
    }

    mysqli_close($con);
}

/* ::::::::::::::::::::::::::::::::: ALL THIS FUNCTIONS ARE CALLED FROM AN AJAX REQUEST ::::::::::::::::::::::::::::::::: */
function connect_from_ajax()
{
    global $response;

    $conn = mysqli_connect(DATABASE_HOST, DATABASE_USER, DATABASE_PW, DATABASE_NAME);

    if (mysqli_connect_errno()) {

        $response['status'] = 'Internal-Error';
        $response['message'] = 'BAD INTERNAL ERROR';
        echo json_encode($response);

        return false;
    } else {

        mysqli_select_db($conn, "airline");
    }

    return $conn;
}

function checkLimit($row, $col)
{
    $letter = range('A', 'Z');

    if ($row < 0 || $row > SEAT_ROW || $col < 'A' || $col > $letter[SEAT_COLUMN - 1])
        return false;
    else
        return true;
}

function manageError($con)
{
    global $response;

    $response['status'] = 'Internal-Error';
    $response['message'] = 'BAD INTERNAL ERROR';
    echo json_encode($response);

    mysqli_rollback($con);
    mysqli_autocommit($con, TRUE);
    mysqli_close($con);
}

/*
 * SELECT must be FOR UPDATE because is called as the first query inside a transaction, just before an update.
 * SELECT is not blocking so despite the transaction two user can conflict on update. SELECT FOR UPDATE will lock
 * the table.
 */
function getSeatStatus($con, $row, $col)
{
    global $response;

    $secure_row = mysqli_real_escape_string($con, $row);
    $secure_col = mysqli_real_escape_string($con, $col);

    $result = array();

    if ($stmt = mysqli_prepare($con, 'SELECT status , owner FROM seats WHERE rowId = ? AND columnId= ? LIMIT 1 FOR UPDATE')) {

        mysqli_stmt_bind_param($stmt, 'is', $secure_row, $secure_col);
      
        if (mysqli_stmt_execute($stmt) == false) {
            manageError($con);
            mysqli_stmt_free_result($stmt);
            mysqli_stmt_close($stmt);
            return false;
        }

        mysqli_stmt_store_result($stmt);

        if (mysqli_affected_rows($con) > 0) {
            mysqli_stmt_bind_result($stmt, $status, $owner);
            mysqli_stmt_fetch($stmt);

            array_push($result, $status);
            array_push($result, $owner);
        } else {

            array_push($result, - 1); // no seat found
        }
    } else {

        manageError($con);
        return false;
    }

    mysqli_stmt_free_result($stmt);
    mysqli_stmt_close($stmt);
    return $result;
}

function updateBookSeat($con, $row, $col)
{
    global $response;

    $secure_row = mysqli_real_escape_string($con, $row);
    $secure_col = mysqli_real_escape_string($con, $col);

    if ($stmt = mysqli_prepare($con, "UPDATE seats SET status=1 , owner = ? WHERE rowId = ? AND columnId= ?")) {

        mysqli_stmt_bind_param($stmt, 'sis', $_SESSION['name'], $secure_row, $secure_col);
    
        if (mysqli_stmt_execute($stmt) == false) {

            manageError($con);
            mysqli_stmt_close($stmt);

            return false;
        }
    } else {

        manageError($con);

        return false;
    }

    mysqli_stmt_close($stmt);
    return true;
}

function insertBookSeat($con, $row, $col)
{
    global $response;

    $secure_row = mysqli_real_escape_string($con, $row);
    $secure_col = mysqli_real_escape_string($con, $col);
    $book = 1;

    if ($stmt = mysqli_prepare($con, "INSERT INTO seats(rowId,columnId,status,owner) VALUES (?,?,?,?)")) {

        mysqli_stmt_bind_param($stmt, 'isis', $secure_row, $secure_col, $book, $_SESSION['name']);

        if (mysqli_stmt_execute($stmt) == false) {

            manageError($con);
            mysqli_stmt_close($stmt);

            return false;
        }
    } else {

        manageError($con);
        return false;
    }

    mysqli_stmt_close($stmt);
    return true;
}

function unbookSeat($con, $row, $col)
{
    global $response;

    $secure_row = mysqli_real_escape_string($con, $row);
    $secure_col = mysqli_real_escape_string($con, $col);
    $book = 1;

    if ($stmt = mysqli_prepare($con, "DELETE FROM seats WHERE rowId=? AND columnId=? AND status=? AND owner=?")) {

        mysqli_stmt_bind_param($stmt, 'isis', $secure_row, $secure_col, $book, $_SESSION['name']);

        if (mysqli_stmt_execute($stmt) == false) {

            manageError($con);
            mysqli_stmt_close($stmt);
            return false;
        }
    } else {

        manageError($con);
        return false;
    }

    mysqli_stmt_close($stmt);
    return true;
}

function updateBuySeat($con, $row, $col)
{
    global $response;

    $secure_row = mysqli_real_escape_string($con, $row);
    $secure_col = mysqli_real_escape_string($con, $col);

    if ($stmt = mysqli_prepare($con, 'UPDATE seats SET status=2 WHERE rowId = ? AND columnId= ?')) {

        mysqli_stmt_bind_param($stmt, 'is', $secure_row, $secure_col);

        if (mysqli_stmt_execute($stmt) == false) {

            manageError($con);
            mysqli_stmt_close($stmt);
            return false;
        }
    } else {

        manageError($con);
        return false;
    }

    mysqli_stmt_close($stmt);
    return true;
}

function insertBuySeat($con, $row, $col)
{
    global $response;
    $book = 2;

    $secure_row = mysqli_real_escape_string($con, $row);
    $secure_col = mysqli_real_escape_string($con, $col);

    if ($stmt = mysqli_prepare($con, "INSERT INTO seats(rowId,columnId,status,owner) VALUES (?,?,?,?)")) {

        mysqli_stmt_bind_param($stmt, 'isis', $secure_row, $secure_col, $book, $_SESSION['name']);

        if (mysqli_stmt_execute($stmt) == false) {

            manageError($con);
            mysqli_stmt_close($stmt);
            return false;
        }
    } else {
        manageError($con);
        return false;
    }

    mysqli_stmt_close($stmt);
    return true;
}



?>